/**
 * Tier A+ Sprint 3 — A2 weekly-briefing hook.
 *
 * Reads the most recent `weekly_briefings` row for the current contractor.
 * The briefing is generated by /api/cron/weekly-briefing (Mondays 8am UTC)
 * once per ISO week per contractor. The hook returns the latest row's
 * rendered text + generation metadata.
 *
 * Tier A+ compliance:
 *   • Read-only — hook never triggers an LLM call
 *   • Contractor-scoped — RLS on `weekly_briefings` filters to the user
 *   • Graceful-degrade — returns null when no row, table missing, or error
 */
import { useQuery } from "@tanstack/react-query";
import { createClient } from "@/lib/supabase/client";

export interface WeeklyBriefingRow {
  id: string;
  contractor_id: string;
  output: string;
  generated_at: string;
  period_start: string;
}

export function useWeeklyBriefing(contractorId: string | null | undefined) {
  return useQuery({
    queryKey: ["weekly-briefing", contractorId],
    queryFn: async (): Promise<WeeklyBriefingRow | null> => {
      if (!contractorId) return null;
      const supabase = createClient();

      const { data, error } = await supabase
        .from("weekly_briefings")
        .select("id, contractor_id, output, generated_at, period_start")
        .eq("contractor_id", contractorId)
        .order("generated_at", { ascending: false })
        .limit(1)
        .maybeSingle();

      if (error || !data) return null;

      return {
        id: data.id as string,
        contractor_id: data.contractor_id as string,
        output: data.output as string,
        generated_at: data.generated_at as string,
        period_start: data.period_start as string,
      };
    },
    enabled: !!contractorId,
    staleTime: 60 * 60 * 1000, // 1h — briefing only changes weekly
    refetchOnWindowFocus: false,
  });
}
