"use client";

/**
 * Tier A+ Sprint 3 — A2 weekly-briefing banner.
 *
 * Renders at the top of the dashboard: a single 3-4 sentence narrative
 * generated by the A2 agent every Monday morning per contractor. The
 * banner is collapsible — first render is expanded, the contractor can
 * collapse it and the choice persists in localStorage.
 *
 * Hides entirely when:
 *   • No briefing row exists for this contractor (cron hasn't fired yet)
 *   • The hook returned null (production graceful-degrade)
 *
 * Tier A+ compliance:
 *   • Disclaimer rendered every render
 *   • "AI briefing" tag distinguishes LLM content
 *   • Read-only — banner is purely informational
 *   • No homeowner names appear (the agent prompt forbids them)
 */

import { useEffect, useState } from "react";
import { ChevronDown, ChevronUp, X } from "lucide-react";
import { useWeeklyBriefing } from "@/hooks/useWeeklyBriefing";
import { AGENT_DISCLAIMER } from "@/lib/agents/orchestrator";

const STORAGE_KEY = "henri:weekly-briefing-collapsed";
const DISMISS_KEY = "henri:weekly-briefing-dismissed-week";

function isoWeekKey(d: Date): string {
  // Returns e.g. "2026-W18" — matches the briefing's period_start week.
  const year = d.getUTCFullYear();
  const onejan = new Date(Date.UTC(year, 0, 1));
  const week = Math.ceil(((d.getTime() - onejan.getTime()) / 86400000 + onejan.getUTCDay() + 1) / 7);
  return `${year}-W${String(week).padStart(2, "0")}`;
}

export function WeeklyBriefingBanner({
  contractorId,
}: {
  contractorId: string | null | undefined;
}) {
  const { data: briefing } = useWeeklyBriefing(contractorId);
  const [collapsed, setCollapsed] = useState(false);
  const [dismissedWeek, setDismissedWeek] = useState<string | null>(null);

  /* Restore collapsed + dismissed-week from localStorage on mount. The
   * one-shot hydration is the standard Henri client-state pattern (see
   * dashboard/page.tsx, settings/territories, etc). */
  useEffect(() => {
    try {
      // eslint-disable-next-line react-hooks/set-state-in-effect -- one-shot localStorage hydration after mount
      setCollapsed(localStorage.getItem(STORAGE_KEY) === "1");
      setDismissedWeek(localStorage.getItem(DISMISS_KEY));
    } catch {
      // Storage disabled — treat as expanded + not-dismissed
    }
  }, []);

  if (!briefing?.output) return null;

  // If the contractor dismissed THIS week's briefing, hide it (re-renders
  // again next Monday once a fresh row lands).
  const briefingWeek = briefing.period_start
    ? isoWeekKey(new Date(briefing.period_start))
    : null;
  if (briefingWeek && dismissedWeek === briefingWeek) return null;

  const onToggle = () => {
    const next = !collapsed;
    setCollapsed(next);
    try {
      localStorage.setItem(STORAGE_KEY, next ? "1" : "0");
    } catch {
      // ignore
    }
  };

  const onDismiss = () => {
    if (!briefingWeek) return;
    setDismissedWeek(briefingWeek);
    try {
      localStorage.setItem(DISMISS_KEY, briefingWeek);
    } catch {
      // ignore
    }
  };

  return (
    <div className="border-b border-warm/30 bg-warm/5">
      <div className="mx-auto flex max-w-screen-xl items-start gap-3 px-4 py-2">
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2">
            <span className="rounded bg-warm/15 px-1.5 py-0.5 text-[10px] font-medium uppercase tracking-wider text-warm">
              AI briefing
            </span>
            <h3 className="font-heading text-sm font-medium text-foreground">
              Your week ahead
            </h3>
            <button
              type="button"
              onClick={onToggle}
              aria-expanded={!collapsed}
              aria-label={collapsed ? "Expand briefing" : "Collapse briefing"}
              className="rounded p-1 text-muted-foreground hover:bg-accent hover:text-foreground transition-colors"
            >
              {collapsed ? (
                <ChevronDown className="h-3 w-3" />
              ) : (
                <ChevronUp className="h-3 w-3" />
              )}
            </button>
          </div>

          {!collapsed && (
            <>
              <p className="mt-1.5 text-sm leading-relaxed text-foreground">
                {briefing.output}
              </p>
              <p className="mt-1.5 text-[10px] text-muted-foreground">
                {AGENT_DISCLAIMER}
              </p>
            </>
          )}
        </div>

        <button
          type="button"
          onClick={onDismiss}
          aria-label="Dismiss this week's briefing"
          className="shrink-0 rounded p-1 text-muted-foreground hover:bg-accent hover:text-foreground transition-colors"
        >
          <X className="h-3 w-3" />
        </button>
      </div>
    </div>
  );
}
