-- 00014_seed_permit_sources.sql
-- Seeds top permit data API sources into permit_sources table
-- Priority: daily update frequency, no/free auth, Socrata first (scraper ready), then ArcGIS

BEGIN;

INSERT INTO permit_sources (source_key, name, state, city, jurisdiction, endpoint, source_type, auth, update_freq, id_field, type_field, status_field, desc_field, address_field, date_field, value_field, lat_field, lng_field)
VALUES

-- ── SOCRATA SOURCES (daily) ───────────────────────────────────────────────────

('socrata_chicago',    'Chicago Building Permits',             'IL', 'Chicago',      'City of Chicago',        'https://data.cityofchicago.org/resource/ydr8-5enu.json',       'socrata', 'socrata_token', 'daily',  'id',            'permit_type',      'permit_status',   'work_description',  'street_address',   'issue_date',    'reported_cost',      'latitude',  'longitude'),
('socrata_la',         'Los Angeles Building Permits',         'CA', 'Los Angeles',  'City of Los Angeles',    'https://data.lacity.org/resource/nbyu-2ha9.json',              'socrata', 'socrata_token', 'weekly', 'pcis_permit',   'permit_type',      'status',          'work_description',  'address',          'issue_date',    'valuation',          'latitude',  'longitude'),
('socrata_nyc',        'New York City Building Permits',       'NY', 'New York',     'City of New York',       'https://data.cityofnewyork.us/resource/ipu4-2vj7.json',        'socrata', 'socrata_token', 'daily',  'job__',         'job_type',         'job_status',      'job_description',   'house__street_name','filing_date',   'initial_cost',       'latitude',  'longitude'),
('socrata_houston',    'Houston Building Permits',             'TX', 'Houston',      'City of Houston',        'https://data.houstontx.gov/resource/4wij-ktsw.json',           'socrata', 'socrata_token', 'daily',  'match_id',      'permit_type',      'status_current',  'project_description','street_address',  'applied_date',  'estimated_value',    'latitude',  'longitude'),
('socrata_phoenix',    'Phoenix Building Permits',             'AZ', 'Phoenix',      'City of Phoenix',        'https://data.phoenix.gov/resource/m5q3-fxjn.json',             'socrata', 'socrata_token', 'daily',  'permit_number', 'type',             'status',          'description',       'address',          'applied_date',  'valuation',          'latitude',  'longitude'),
('socrata_denver',     'Denver Building Permits',              'CO', 'Denver',       'City of Denver',         'https://data.denvergov.org/resource/c5tk-bn43.json',           'socrata', 'socrata_token', 'daily',  'permit_number', 'permit_type_name', 'status',          'work_description',  'full_address',     'issue_date',    'value',              'latitude',  'longitude'),
('socrata_austin',     'Austin Construction Permits',          'TX', 'Austin',       'City of Austin',         'https://data.austintexas.gov/resource/3syk-w9eu.json',         'socrata', 'socrata_token', 'daily',  'permitnum',     'workclass',        'status_current',  'description',       'original_address1','applied_date',  'total_valuation',    'latitude',  'longitude'),
('socrata_seattle',    'Seattle Building Permits',             'WA', 'Seattle',      'City of Seattle',        'https://data.seattle.gov/resource/76t5-zqzr.json',             'socrata', 'socrata_token', 'daily',  'permitnum',     'permitclass',      'statuscurrent',   'description',       'originaladdress1', 'applieddate',   'estprojectcost',     'latitude',  'longitude'),
('socrata_seattle_lu', 'Seattle Land Use Permits',             'WA', 'Seattle',      'City of Seattle',        'https://data.seattle.gov/resource/uyyd-8gak.json',             'socrata', 'socrata_token', 'daily',  'applicationno', 'permitclass',      'statuscurrent',   'description',       'originaladdress1', 'applieddate',   'estprojectcost',     'latitude',  'longitude'),
('socrata_baltimore',  'Baltimore Building Permits',           'MD', 'Baltimore',    'City of Baltimore',      'https://data.baltimorecity.gov/resource/fesm-tgxf.json',       'socrata', 'socrata_token', 'daily',  'permitno',      'permittype',       'statusdate',      'description',       'propertyaddress',  'dateissued',    'projectedcost',      'lat',       'lng'),
('socrata_miami_dade', 'Miami-Dade Building Permits',         'FL', 'Miami',        'Miami-Dade County',      'https://opendata.miamidade.gov/resource/vvw2-gpfq.json',       'socrata', 'socrata_token', 'daily',  'permit_number', 'permit_type',      'permit_status',   'scope_of_work',     'site_address',     'issue_date',    'estimated_value',    'latitude',  'longitude'),
('socrata_cincinnati', 'Cincinnati Building Permits',         'OH', 'Cincinnati',   'City of Cincinnati',     'https://data.cincinnati-oh.gov/resource/uhjb-xac9.json',       'socrata', 'socrata_token', 'daily',  'apnbr',         'ptype',            'pstatus',         'pdesc',             'siteaddr',         'appldt',        'dclaredvalu',        'lat',       'lng'),
('socrata_sf',         'San Francisco Building Permits',      'CA', 'San Francisco','City of San Francisco',  'https://data.sfgov.org/resource/i98e-djp9.json',               'socrata', 'socrata_token', 'weekly', 'permit_number', 'permit_type',      'status',          'description',       'street_address',   'filed_date',    'estimated_cost',     'latitude',  'longitude'),
('socrata_santa_monica','Santa Monica Building Permits',      'CA', 'Santa Monica', 'City of Santa Monica',   'https://data.smgov.net/resource/ng8m-khuz.json',               'socrata', 'socrata_token', 'weekly', 'permit_no',     'permit_type',      'status',          'description',       'address',          'issue_date',    'valuation',          'lat',       'lon'),
('socrata_berkeley',   'Berkeley Building Permits',           'CA', 'Berkeley',     'City of Berkeley',       'https://data.cityofberkeley.info/resource/q6ea-cfdd.json',     'socrata', 'socrata_token', 'weekly', 'permitid',      'type',             'statename',       'description',       'location',         'issuedate',     'valueconstruction',  'latitude',  'longitude'),
('socrata_nola',       'New Orleans Permits',                 'LA', 'New Orleans',  'City of New Orleans',    'https://data.nola.gov/resource/bhcb-iugi.json',                'socrata', 'socrata_token', 'daily',  'permit_number', 'permit_type',      'permit_status',   'description',       'site_address',     'issue_date',    'estimated_value',    'latitude',  'longitude'),
('socrata_nashville',  'Nashville Building Permits',          'TN', 'Nashville',    'City of Nashville',      'https://data.nashville.gov/resource/3h5w-q8b7.json',           'socrata', 'socrata_token', 'daily',  'permit_number', 'permit_type',      'status',          'description',       'address',          'permit_date',   'estimated_cost',     'latitude',  'longitude'),
('socrata_louisville', 'Louisville Building Permits',         'KY', 'Louisville',   'City of Louisville',     'https://data.louisvilleky.gov/resource/e56e-cqyv.json',        'socrata', 'socrata_token', 'daily',  'permit_number', 'permit_type',      'status',          'work_description',  'street_address',   'issue_date',    'declared_valuation', 'latitude',  'longitude'),
('socrata_honolulu',   'Honolulu Building Permits',           'HI', 'Honolulu',     'City of Honolulu',       'https://data.honolulu.gov/resource/eb2h-h5x9.json',            'socrata', 'socrata_token', 'daily',  'permit_number', 'permit_type',      'status',          'description',       'address',          'issue_date',    'estimated_value',    'latitude',  'longitude'),
('socrata_montgomery', 'Montgomery County Permits',           'MD', 'Rockville',    'Montgomery County MD',   'https://data.montgomerycountymd.gov/resource/au8e-bpsa.json',  'socrata', 'socrata_token', 'daily',  'permitno',      'type',             'status',          'description',       'stno',             'issuedate',     'buildingvalue',      'latitude',  'longitude'),
('socrata_sd',         'San Diego Building Permits',          'CA', 'San Diego',    'City of San Diego',      'https://data.sandiego.gov/resource/a4vq-h4bd.json',            'socrata', 'none',          'daily',  'permitno',      'type',             'status',          'scope',             'address',          'issue_dt',      'value',              'lat',       'lng'),
('socrata_cleveland',  'Cleveland Building Permits',          'OH', 'Cleveland',    'City of Cleveland',      'https://data.clevelandohio.gov/resource/4iud-ynrb.json',       'socrata', 'socrata_token', 'weekly', 'permit_number', 'permit_type',      'permit_status',   'work_description',  'street_address',   'issue_date',    'estimated_cost',     'latitude',  'longitude'),
('socrata_jersey',     'Jersey City Permits',                 'NJ', 'Jersey City',  'City of Jersey City',    'https://data.jerseycitynj.gov/resource/uvgi-kub4.json',        'socrata', 'socrata_token', 'weekly', 'record_id',     'type',             'status',          'description',       'address',          'date_issued',   'job_value',          'latitude',  'longitude'),
('socrata_milwaukee',  'Milwaukee Building Permits',          'WI', 'Milwaukee',    'City of Milwaukee',      'https://data.milwaukee.gov/resource/b7uh-s5a7.json',           'socrata', 'socrata_token', 'weekly', 'permit_number', 'type',             'status',          'description',       'address',          'issue_date',    'estimated_cost',     'latitude',  'longitude'),
('socrata_buffalo',    'Buffalo Building Permits',            'NY', 'Buffalo',      'City of Buffalo',        'https://data.buffalony.gov/resource/2iak-jxvb.json',           'socrata', 'socrata_token', 'weekly', 'permit_number', 'type',             'status',          'description',       'address',          'issue_date',    'estimated_cost',     'latitude',  'longitude'),

-- ── ARCGIS SOURCES ────────────────────────────────────────────────────────────

('arcgis_atlanta',     'Atlanta Building Permits',            'GA', 'Atlanta',      'City of Atlanta',        'https://dpcd.coaplangis.opendata.arcgis.com/datasets/permits/FeatureServer/0', 'arcgis', 'none', 'weekly', 'PERMIT_NUMBER', 'PERMIT_TYPE', 'STATUS', 'DESCRIPTION', 'ADDRESS', 'ISSUE_DATE', 'ESTIMATED_VALUE', NULL, NULL),
('arcgis_arlington',   'Arlington VA Building Permits',       'VA', 'Arlington',    'Arlington County VA',    'https://gisdata-arlgis.opendata.arcgis.com/datasets/permits/FeatureServer/0',  'arcgis', 'none', 'weekly', 'PERMIT_NUM',   'PERMIT_TYPE', 'STATUS', 'DESCRIPTION', 'ADDRESS', 'ISSUED_DATE','VALUATION',       NULL, NULL),
('arcgis_durham',      'Durham NC Building Permits',          'NC', 'Durham',       'City of Durham',         'https://live-durhamnc.opendata.arcgis.com/datasets/permits/FeatureServer/0',   'arcgis', 'none', 'weekly', 'PERMIT_NUM',   'PERMIT_TYPE', 'STATUS', 'DESCRIPTION', 'ADDRESS', 'ISSUE_DATE', 'VALUATION',       NULL, NULL),
('arcgis_tampa',       'Tampa Building Permits',              'FL', 'Tampa',        'City of Tampa',          'https://gis-tampagov.opendata.arcgis.com/datasets/permits/FeatureServer/0',     'arcgis', 'none', 'weekly', 'PERMITNUM',    'PERMITTYPE',  'STATUS', 'DESCRIPTION', 'ADDRESS', 'ISSUEDATE',  'COST',            NULL, NULL),
('arcgis_sanjose',     'San Jose Building Permits',           'CA', 'San Jose',     'City of San Jose',       'https://gisdata-csj.opendata.arcgis.com/datasets/permits/FeatureServer/0',      'arcgis', 'none', 'weekly', 'PERMIT_NUM',   'PERMIT_TYPE', 'STATUS', 'DESCRIPTION', 'ADDRESS', 'ISSUE_DATE', 'VALUE',           NULL, NULL),
('arcgis_houston',     'Houston Building Permits (GIS)',      'TX', 'Houston',      'City of Houston',        'https://cohgis-mycity.opendata.arcgis.com/datasets/permits/FeatureServer/0',   'arcgis', 'none', 'weekly', 'PERMIT_NUMBER','TYPE',        'STATUS', 'DESCRIPTION', 'ADDRESS', 'APPL_DATE',  'VALUE',           NULL, NULL),
('arcgis_aurora',      'Aurora CO Building Permits',          'CO', 'Aurora',       'City of Aurora',         'https://data-auroraco.opendata.arcgis.com/datasets/permits/FeatureServer/0',   'arcgis', 'none', 'weekly', 'PERMIT_NUM',   'PERMIT_TYPE', 'STATUS', 'DESCRIPTION', 'ADDRESS', 'ISSUE_DATE', 'VALUE',           NULL, NULL),
('arcgis_fairfax',     'Fairfax County Building Permits',     'VA', 'Fairfax',      'Fairfax County VA',      'https://data-fairfaxcountygis.opendata.arcgis.com/datasets/permits/FeatureServer/0', 'arcgis', 'none', 'weekly', 'PERMIT_NO', 'TYPE',      'STATUS', 'DESCRIPTION', 'ADDRESS', 'ISSUE_DATE', 'VALUE',           NULL, NULL),
('arcgis_stpete',      'St Petersburg FL Building Permits',   'FL', 'St Petersburg','City of St Petersburg',  'https://stpete.maps.arcgis.com/apps/opsdashboard/index.html#/permits/FeatureServer/0', 'arcgis', 'none', 'weekly', 'PERMIT_NUM', 'TYPE',    'STATUS', 'DESCRIPTION', 'ADDRESS', 'ISSUED',     'VALUE',           NULL, NULL),
('arcgis_knoxville',   'Knoxville Building Permits',          'TN', 'Knoxville',    'City of Knoxville',      'https://data-cityofknoxville.opendata.arcgis.com/datasets/permits/FeatureServer/0', 'arcgis', 'none', 'weekly', 'PERMIT_NO', 'TYPE',      'STATUS', 'DESCRIPTION', 'ADDRESS', 'ISSUE_DATE', 'VALUE',           NULL, NULL)

ON CONFLICT (source_key) DO NOTHING;

COMMIT;
